document.write("<footer id=\"footer\">");
document.write("        <div class=\"box layer\">");
document.write("            <div class=\"ftop\">");
document.write("                <span>");
document.write("                    <i>© 2020-3-10<\/i>");
document.write("                    <svg class=\"icon\" aria-hidden=\"true\">");
document.write("                        <use xlink:href=\"#icon-xin1\"><\/use>");
document.write("                    <\/svg>");
document.write("                    <i>Melikui<\/i>");
document.write("                <\/span>");
document.write("                <span>|<\/span>");
document.write("                <span class=\"big\">");
document.write("                    <svg class=\"icon\" aria-hidden=\"true\">");
document.write("                        <use xlink:href=\"#icon-tongji1\"><\/use>");
document.write("                    <\/svg>");
document.write("                    <i>站点字数合计: <i id=\"wordCount\">字数统计<\/i><\/i>");
document.write("                <\/span>");
document.write("                <span>|<\/span>");
document.write("                <span>");
document.write("                    <svg class=\"icon\" aria-hidden=\"true\">");
document.write("                        <use xlink:href=\"#icon-beian4\"><\/use>");
document.write("                    <\/svg>");
document.write("                    <a target=\"_blank\" href=\"http:\/\/www.beian.miit.gov.cn\/\">皖ICP备20009100号<\/a>");
document.write("                <\/span>");
document.write("            <\/div>");
document.write("            <div class=\"webRunTime\">本站已安全运行：982 天 19 小时 26 分 57 秒<\/div>");
document.write("            <div class=\"fbottom\">");
document.write("                <span>");
document.write("                    <svg class=\"icon\" aria-hidden=\"true\">");
document.write("                        <use xlink:href=\"#icon-ai-user\"><\/use>");
document.write("                    <\/svg>");
document.write("                    <i>999人<\/i>");
document.write("                <\/span>");
document.write("                <span>|<\/span>");
document.write("                <span>");
document.write("                    <svg class=\"icon\" aria-hidden=\"true\">");
document.write("                        <use xlink:href=\"#icon-yanjing\"><\/use>");
document.write("                    <\/svg>");
document.write("                    <i>666次<\/i>");
document.write("                <\/span>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("    <\/footer>");
