document.write("<header id=\"header\">");
document.write("        <!-- 顶部导航栏版心区域, 1190px -->");
document.write("        <div class=\"container layer clearfix\">");
document.write("            <!-- logo--标题--280*60 -->");
document.write("            <h1 class=\"logo fl\"><a target=\"_self\" href=\".\/index.html\">Melikui<\/a><\/h1>");
document.write("            <!-- 中间导航--600*60 -->");
document.write("            <div class=\"navigation fl\">");
document.write("                <div class=\"menu-fix-box fl\">");
document.write("                    <ul class=\"clearfix\">");
document.write("                        <li class=\"ele\">");
document.write("                            <a target=\"_self\" href=\".\/index.html\">");
document.write("                                <svg class=\"icon\" aria-hidden=\"true\">");
document.write("                                    <use xlink:href=\"#icon-xin1\"><\/use>");
document.write("                                <\/svg>&nbsp;首页<\/a>");
document.write("                        <\/li>");
document.write("                        <li class=\"ele\">");
document.write("                            <a href=\"#\"><svg class=\"icon\" aria-hidden=\"true\">");
document.write("                                    <use xlink:href=\"#icon-biji1\"><\/use>");
document.write("                                <\/svg>&nbsp;日志<\/a>");
document.write("                        <\/li>");
document.write("                        <li class=\"ele\">");
document.write("                            <a href=\"#\"><svg class=\"icon\" aria-hidden=\"true\">");
document.write("                                    <use xlink:href=\"#icon-biji\"><\/use>");
document.write("                                <\/svg>&nbsp;笔记<\/a>");
document.write("                        <\/li>");
document.write("                        <li class=\"ele\">");
document.write("                            <a href=\"#\"><svg class=\"icon\" aria-hidden=\"true\">");
document.write("                                    <use xlink:href=\"#icon-liuyan2\"><\/use>");
document.write("                                <\/svg>&nbsp;留言<\/a>");
document.write("                        <\/li>");
document.write("                        <li class=\"ele\">");
document.write("                            <a href=\"#\"><svg class=\"icon\" aria-hidden=\"true\">");
document.write("                                    <use xlink:href=\"#icon-guanyu2\"><\/use>");
document.write("                                <\/svg>&nbsp;关于<\/a>");
document.write("                        <\/li>");
document.write("                        <li class=\"ele\">");
document.write("                            <a href=\"#\"><svg class=\"icon\" aria-hidden=\"true\">");
document.write("                                    <use xlink:href=\"#icon-share\"><\/use>");
document.write("                                <\/svg>&nbsp;友链<\/a>");
document.write("                        <\/li>");
document.write("                    <\/ul>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("            <!-- 右侧--搜索和时间轴---200*60 -->");
document.write("            <div class=\"right-nav\">");
document.write("                <ul>");
document.write("                    <li><a href=\"#\" title=\"时间轴\">");
document.write("                            <span>");
document.write("                                <svg class=\"icon\" aria-hidden=\"true\">");
document.write("                                    <use xlink:href=\"#icon-shijianzhou1\"><\/use>");
document.write("                                <\/svg>");
document.write("                            <\/span>");
document.write("                        <\/a><\/li>");
document.write("                    <li><i>|<\/i><\/li>");
document.write("                    <li><a href=\"#\" title=\"全局搜索\">");
document.write("                            <span>");
document.write("                                <svg class=\"icon\" aria-hidden=\"true\">");
document.write("                                    <use xlink:href=\"#icon-soushuo\"><\/use>");
document.write("                                <\/svg>");
document.write("                            <\/span>");
document.write("                        <\/a><\/li>");
document.write("");
document.write("                <\/ul>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("    <\/header>");
